AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role assumed by the custom remediation Lambda (Tooling account)

Parameters:
  LambdaRemediationRoleName:
    Type: String
    Default: lambda-s3-remediation-role
    Description: IAM role name assumed by the remediation Lambda function

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaRemediationRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: s3-public-access-remediation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketPublicAccessBlock
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketAcl
                  - s3:PutBucketAcl
                Resource: '*'

Outputs:
  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: tooling-lambda-remediation-role-arn